# Generated by Django 2.0.6 on 2018-07-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('registDate', models.DateTimeField(verbose_name='date registed')),
            ],
        ),
        migrations.CreateModel(
            name='userInformation',
            fields=[
                ('user_Identity_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('user_Identity_name', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginPages.user')),
            ],
        ),
    ]
