# Generated by Django 2.0.6 on 2018-08-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userfiles',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_file', models.FileField(upload_to='./upload/')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='offline', max_length=20),
        ),
        migrations.DeleteModel(
            name='userInformation',
        ),
    ]
